server:
  port: 18888

spring:
  application:
    name: ts-assurance-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: ts-assurance-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: assurance.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831