spring:
  application:
    name: ts-station-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: ts-station-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831