# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
swagger:
  controllerPackage: travel2.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    sampler-type: const
    sampler-param: 1