server:
  port: 12342

spring:
  application:
    name: ts-user-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: ts-user-mongo
      database: ts-user-mongo
      port: 27017

swagger:
  controllerPackage: user.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831