server:
  port: 18898

spring:
  application:
    name: ts-seat-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  controllerPackage: seat.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831