server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831