spring:
  application:
    name: ts-route-plan-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831