# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  controllerPackage: ticketinfo.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831